name: Generate

on:
  push:
    # branches: [ master ]
    branches: [ generate ]
    paths-ignore:
      - './README.md'

jobs:
  generateCode:
    name: Generate Code
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Generate All Codes
        run: python ./scripts/generate.py

      - name: Publish C#
        uses: actions/upload-artifact@v3
        with:
          name: GeneratedCS
          path: ./generated/cs/
          if-no-files-found: error
          retention-days: 1

      - name: Publish Python
        uses: actions/upload-artifact@v3
        with:
          name: GeneratedPython
          path: ./generated/python/
          if-no-files-found: error
          retention-days: 1

  publishCS:
    name: Publish C#
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: GeneratedCS
          path: ./

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
        
      - name: Build
        run: dotnet build ./Constants.csproj

      - name: Packing
        run: dotnet pack ./Constants.csproj

      - name: Nuget Pushing
        run: |
          dotnet nuget push \
          ./bin/Debug/Constants.*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json



# jobs:
#   build:
#     name: C# Build
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v2
#       with:
#         dotnet-version: 3.1.x
#     - name: Build
#       run: dotnet build ./ApolloRoboto.Constants.csproj
  
#   publish:
#     name: C# Publish to Nuget
#     runs-on: ubuntu-latest
#     needs: [ build ]

#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v2
#         with:
#           dotnet-version: 3.1.x
#       - name: Packing
#         run: dotnet pack ./ApolloRoboto.Constants.csproj
#       - name: Nuget Pushing
#         run: |
#           dotnet nuget push \
#           ./bin/Debug/ApolloRoboto.Constants.*.nupkg \
#           --api-key ${{ secrets.NUGET_API_KEY }} \
#           --source https://api.nuget.org/v3/index.json